export default interface signUpData {
    first_name : string,
    last_name : string,
    username : string,
    password : string,
    email : string,
    phone_number : string,
    student_id : string,
    academic_year : number,
    section  : string,
    department : number,
    gender : string,
    telegram : string,
    instagram : string,
    linkedin : string,
  }